name: Build Android App Bundle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create Missing Settings File if Needed
        run: |
          if [ ! -f "settings.gradle" ] && [ ! -f "settings.gradle.kts" ]; then
            echo "include ':app'" > settings.gradle
          fi

      - name: Build Release App Bundle (AAB)
        run: |
          gradle wrapper --gradle-version 8.7
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Sign App Bundle
        run: |
          keytool -genkey -v -keystore release.keystore -keyalg RSA -keysize 2048 -validity 10000 -alias upload-key -storepass pakblood123 -keypass pakblood123 -dname "CN=PakBloodPortal, OU=App, O=Org, L=Lahore, S=Punjab, C=PK"
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore release.keystore -storepass pakblood123 -keypass pakblood123 app/build/outputs/bundle/release/*.aab upload-key

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed-aab
          path: "app/build/outputs/bundle/release/*.aab"

      - name: Upload Keystore (Save this file safely!)
        uses: actions/upload-artifact@v4
        with:
          name: release-keystore
          path: release.keystore
