name: Build Android App Bundle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Release App Bundle (AAB)
      run: |
        if [ -f "gradlew" ]; then
          chmod +x gradlew
          ./gradlew :app:bundleRelease
        else
          gradle wrapper
          chmod +x gradlew
          ./gradlew :app:bundleRelease
        fi

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-aab
        path: "**/build/outputs/bundle/release/app-release.aab"
