name: Build Android App Bundle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create Missing Settings File if Needed
        run: |
          if [ ! -f "settings.gradle" ] && [ ! -f "settings.gradle.kts" ]; then
            echo "include ':app'" > settings.gradle
          fi

      - name: Build Release App Bundle (AAB)
        run: |
          gradle wrapper --gradle-version 8.7
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Decode Keystore & Sign App Bundle
        run: |
          echo "MIIKvAIBAzCCCnIGCSqGSIb3DQEHAaCCCmMEggpfMIIKWzCCBLIGCSqGSIb3DQEHBqCCBKMwggSfAgEAMIIEmAYJKoZIhvcNAQcBMFcGCSqGSIb3DQEFDTBKMCkGCSqGSIb3DQEFDDAcBAjxMemEa6XSmwICCAAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEJcD0ZCUCC85KcPJRwGGS5OAggQwEFE4tPKVm6YepfhsZy43S8dJWLeUXhsYmBAhc3kvALbq+cNlGrJxKQHPVT/R0HZSxoKXScUGt5ry29yt5g4W0kBxIl7v2Jwbro/hllHz7T++8Xk8RYVVQ4Hrhkw9YB6KJ1qkh3ohLa+Cx4A9l/qG1aa1RPy95nNqHbtX5o8WohX7ZTr+uRFt7Wb6eeWq313sC0amE33OUgpuXckUL325VdHbCKRPKjfmsmXZa/lw8Y7RPDgCCZ8Kehi8tJ93Goxxa8DWmPf2EdufenLhxJNpKcPA6ISuX1lF3AWAvyYEGRU+SZgb8WjrlcNfeQV4RGVSD6E6zsiL5gD8xAC5csft1etUjJE1fpM2mw1jv0sxvxqxz9RsVuTNT7U9HPz0eDiCLxOXDHQ7sgfSyWenOfdeluz6GVZoZO9QIXoft2eKvEEaD4cN9dcoZeXynp6AiobCH9bfuGDG++9L4SUWwCC07AT8GhjLEaQVOSFvMwUcd4BIJpye/bkd0C5Ib+vhi4ic5xFVxbMnRAyIMQLRaBI0w6paPQHtH+PFV4M+w8/XDl0XXKvTSbxIR8C0cuSYnoZrCcZgvpCSi0nL6AA7hmHjBaykhtz6jlsdCwajQxZmB5AhHp/MWt1u7aSZWF+sK3sjT6bX8yyQRuc2ztAvW2cvwQ69V1kdf9WszI75WnnQ0OnuNigBA/xZ8WoKJZpcqfMXgyp0jMIc1FL6dshlIL00eYxmRkMHjFh2P2Cm3JplN0EHtsLwa/zcr5FdT5meQFxjZXlPQB15GaSjsf3XVzPjQdT8kPQXv7/EWoRqIjcgAwVNB4M8g4XuO5WmY94ZeZgMPnHKVGL987zZ66FPM3Or/2T5oYuXXL6k1Byemr/tEJvmTKNTjbdWW9z0vOy5reuRZNYAUJS9S1dBrKi5q/fMSSriW5TiNFr8Rh13sT4m1qyXD7iHMlpWnijqzmnJJPlhEIP5ql8LCm2DW1PaH2qswxzsJ0SuvksVInXjy9ufziPh6WmV2+Ca9Ykab0kP8tLENaUTIqD86gabvAPGpCMhN2t2c9UFRTu//jmG14AzFyRPV35M7g/AGcL5udrEmi05BWl621o2JRXmmhUez71B2BUQB6dL9yPTHKhqQ3EXS00Hzm+9Q3eIaijACAj+t++21/mTz1QHUl5DNVhzF7wYCxeLSdyrm+eGYME8In9uk/4Jhoohtq3iU3hASSS9rmYXUt3K72RKPvjta2ehg7PeRfewK7gAkMheyrbjgky4ImTWK8V65EZw6BuUlGS4I56V5nzPIJ5w13LX9rTj/Uuyy75K6N56Bo9FIovYhM7oR9hVmp+Q7ls5bHeyMHSQPXpI9n0aDUg28XYxj3G/oUh25FyunZbXWU1EQG3fijSHMQ6tk7YpKiqkuy+H3p/rL28oQfGZMgnFEAK5TQ5P8b+XfjCCBaEGCSqGSIb3DQEHAaCCBZIEggWOMIIFijCCBYYGCyqGSIb3DQEMCgECoIIFMTCCBS0wVwYJKoZIhvcNAQUNMEowKQYJKoZIhvcNAQUMMBwECH9EZ+zaJfooAgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQlPQ2Z10x33hoPTRkaxrfAwSCBNDBv+huuNfka0hcCJ/vh9wb/84ZKnamC6M+ubLq5cQ/i41uTZlkP58ZI1NN+NwM+fgso7xHylOBhiV9iC9re4jEyrXA90rKrIlvObI2xbhhIire39/s+WYBTfjuEMc940d0Bob1aMLqBpQCt1ZmfriMnp2T0CsQ4AR1xOG9dENAn9+tOXc+BjsflFCUbooQLK5WUsr652YAkBj/4sIo4fC3AakwB8i1Wjfose2G2jHOtCKW3DmkGPPfQ7uwZt9KY5ZOI2lKEAgl7a8ubCb7f4zENTGHS3pnIw8ACtjw8rActaodo+a0gEGO2rwobYqQl1223bRApcLbFnkZtiv4W5ji4VAvHIj7/PGlqQcAMFsJwR7wE5fxK6JnCQ/6Y6Ffg28ufTn6Gyx8NLK7L4Pisy1Ewvqw3B3enzaW0e0Q6jlz24eSn9vgNT2L+3LQpdTx6UlIK0plcazI5YmMdkqrdUy1DNiUEiZz4ibYMvXUVBqHU6+Ghnl5v7AeDyV3DM/7e2gZtAmgEP3gIavH/vlx6l4+icXZrrrh31UHHm1MjoYO1wUjFpKhSQ0rrX6RSOxC1H0lWfOnb2WmBuChUlA661FJjj1BNYDokjPle0IdjaEqzMhtZET40gFOQ+YKnTRPBdJp3iFdQHn4Ldu/nsLDfh7Bti3h2TSQpainIdI34SdADol7me9vF8caXII+gMi0gimw+/pQBCB0ouPVdBnOZB4t1WCxUF6FHaW+6q490R7gdXztC0Klb2I35ALfPDYbWeEXFKeica0hm6y5EjVximyAffWflCh1HMdUeW0XABuSd/8x6J/5zD+vdkyZhvoQ67+Q0OGsqjaJxqDGphBqKH1UdLjIbtgRsKnHTX8QShuV2zk58fgN+gcclWRR2p8IAAItAqMMfJyPiHZTWOaUbcfFilPyn2kkDYwTfi9h/+joxCIEP8paX0+7z5uLOE9Dg8l9u0sbBa0aIC5hEjmtTZ9sQ7rFh1e36mjEHWR7pcCfZGGYDXpQQk0HKzO8Qu/RGr2lP+Z87m+nH50yICbySCTMbSLmy155hsUbQ+rbW59vJcJJCD6DsSdgWPF/8pAJuQJNt8AFoIKv9LJBVXylTjakMHj7LmePin3pPHAczpN6fzWgPEwR+Nvy7TdQrbZXsxAodVi8vzfMCA6RzwO70F07gL2cSKXQE3FTS7Gp1gxoYy15UFU4CVHTyjblashKEgyjftl7dFLIguqhHlmlb9E3nd3UVZM9JRnCFCgf/OJx545rPGP+UDncrFbYh6hSa0vMuoeaj7XxtTRboDvCVU0EL/0D3jPJhpZzmKydE9X0OGQobRRTe2qqWUH5X+cotAhi2RpbB4XJ274xxTu/Y1rhMSrR8E6q1fqy/7rnexmObc00zvx0BbTt6hi+EItuO5JXThP45f5kuqYGSL0PJIOHq+BYKG1Up7oCgqAdUWWSPnREVTdwouUf12o4doSM+y7nmboSeVsMpFN1fciQ1xtexMRsWTziaD7oShj8EsXQAoLIPNKg0wzvnRf8IVHae48xGBsTRr4d1w4qmxaSrCgyWCpsO4hFHuLOFvxRYG9Qv9jaQTcbOe1BRpqndMa6Wa+gLwcixswEy5rxQhsQ1r9PeInFGTszbFZfejo4sUAj0TFCMBsGCSqGSIb3DQEJFDEOHgwAdQBwAGwAbwBhAGQwIwYJKoZIhvcNAQkVMRYEFOzTIHl1zkTdCU/3Yn37aGKHHspyMEEwMTANBglghkgBZQMEAgEFAAQgab22bC+iHmGyE/VVm3vVAHgccytMw7WKE9iyZtuEHj8ECIVyQRCCFo4cAgIIAA==" | base64 -d > upload-keystore.jks
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore upload-keystore.jks -storepass pakblood123 -keypass pakblood123 app/build/outputs/bundle/release/*.aab upload

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed-aab
          path: "app/build/outputs/bundle/release/*.aab"
